### ISSUE TITLE
input from CLI args not working

### ISSUE THREAD

**Issue by bbusschots-mu** [Delapouite/emmet-cli#2]
When I try to use the example from the docs:

```
emmet '#foo>span.bar*3'
```

The console never returns, it just sits there as if expecting input. If I use the piped example all is as expected.

Having to always pipe is very annoying, it would be great if this little bug could be nipped in the bud.

**Comment by Delapouite** [comment]
Hi. It should be fixed in 1.2.1.

Thanks for the report.
